In [1]:
import pandas as pd

data = pd.read_csv(r"digit recognizor.csv")

In [2]:
X = data.iloc[:, 1:]
y = data.iloc[:, 0]

In [3]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold

In [4]:
X_fsvar = VarianceThreshold(np.median(X.var().values)).fit_transform(X)

In [5]:
X_fsvar.shape

(42000, 392)

In [6]:
from sklearn.feature_selection import f_classif

In [7]:
F, pvalues_f = f_classif(X_fsvar, y)

In [8]:
F

array([ 618.65383492,  846.18897012, 1115.40617051, 1362.3677305 ,
       1452.03355369, 1381.09095571, 1138.26505266,  464.29616121,
        660.00977785,  849.66393412, 1004.7450309 , 1124.76177588,
       1200.99190762, 1209.29489877, 1110.4944286 ,  854.66183292,
        577.52063451,  342.09729054,  178.67397866,  118.01145533,
        612.12261014,  899.40904291, 1196.17528948, 1424.49864852,
       1569.26556677, 1742.49910702, 1910.98023795, 1969.20520223,
       1731.37475948, 1295.09668012,  839.15325001,  531.97951763,
        371.82392681,  336.00820537,  378.93378743,  317.47025479,
        528.94881012,  766.40792176,  947.63168717, 1086.0472161 ,
       1177.72017709, 1253.79641973, 1344.06961068, 1507.33781169,
       1616.50454434, 1512.25864876, 1289.65180587, 1051.26276412,
        839.48869386,  680.07426932,  600.85538567,  633.55772663,
        683.96908509,  347.65867784,  452.76238211,  509.16387684,
        515.7498157 ,  532.86107778,  594.62512658,  664.18740

In [9]:
pvalues_f

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 4.71193533e-220,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

In [10]:
k = F.shape[0] - (pvalues_f > 0.05).sum()

In [11]:
k

392

In [12]:
from sklearn.feature_selection import mutual_info_classif as MIC

In [13]:
result = MIC(X_fsvar, y)

In [14]:
result

array([0.05325243, 0.06630002, 0.0769316 , 0.0932455 , 0.0860874 ,
       0.08413158, 0.06925373, 0.04668355, 0.05603749, 0.07224748,
       0.09118952, 0.09833349, 0.11029442, 0.11062456, 0.10215402,
       0.08654359, 0.06304876, 0.04326092, 0.02953989, 0.01905503,
       0.05258973, 0.06964882, 0.08573836, 0.108821  , 0.12315361,
       0.14900069, 0.15521598, 0.16984056, 0.14626289, 0.1254045 ,
       0.09155566, 0.06223936, 0.04683617, 0.04169885, 0.03477092,
       0.03025535, 0.04696682, 0.06346414, 0.0783656 , 0.08765416,
       0.09624349, 0.10094024, 0.11339398, 0.12085546, 0.13165091,
       0.11516681, 0.10832229, 0.08289237, 0.07861588, 0.06750474,
       0.05398527, 0.05466185, 0.05561175, 0.04085677, 0.04773971,
       0.05056104, 0.05457999, 0.05860936, 0.06082066, 0.05882635,
       0.06127311, 0.0687974 , 0.07348185, 0.07675371, 0.06823332,
       0.07326432, 0.07173088, 0.07646313, 0.07067462, 0.06074132,
       0.05987824, 0.03409147, 0.04299936, 0.04782358, 0.04728

In [15]:
k = result.shape[0] - sum(result <= 0)