In [2]:
import torch

In [3]:
A = torch.arange(20).reshape(5, 4)

In [4]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [6]:
B = A.clone()
B

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [8]:
X = torch.arange(24).reshape(2, 3, 4)
a = 2

In [9]:
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [10]:
X = torch.arange(4, dtype=torch.float32)
X.sum()

tensor(6.)

In [11]:
A = torch.arange(40).reshape(2, 5, 4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [12]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [13]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [14]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

In [15]:
print(A.mean())
print(A.numel())
print(A.sum() / A.numel())

tensor(9.5000)
20
tensor(9.5000)


In [16]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [17]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [18]:
sum_A = A.sum(axis=1, keepdims=True)  # keepdims=True不丢掉维度，否则三维矩阵按一个维度求和就会变为二维矩阵，二维矩阵若按一个维度求和就会变为一维向量

In [19]:
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [20]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [21]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [22]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

In [23]:
torch.dot(x, y)

tensor(6.)

In [24]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4, dtype=torch.float32)

In [28]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [29]:
x

tensor([0., 1., 2., 3.])

In [25]:
torch.mv(A, x)  # 矩阵向量积

tensor([ 14.,  38.,  62.,  86., 110.])

In [26]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = torch.ones(4, 3)

In [27]:
torch.mm(A, B)  # 矩阵相乘

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [30]:
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))  # L2范数

tensor(5.)


In [31]:
u = torch.tensor([3.0, -4.0])
print(torch.abs(u).sum())  # L1范数

tensor(7.)


In [32]:
# 弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根
print(torch.norm(torch.ones((4, 9))))  # 把矩阵拉成一个向量，然后再求和

tensor(6.)
