In [1]:
import torch

In [2]:
x = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(x, x)

In [3]:
y.backward()

In [4]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
x.grad.zero_()  # y.backward() 后才能产生梯度，才能梯度清零，没有反向传播，无法梯度清零

tensor([0., 0., 0., 0.])

In [7]:
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(x, x)
y.backward()
# 默认情况下，PyTorch会累积梯度，需要清除之前的值
# 对非标量调用 'backward' 需要传入一个 'gradient' 参数，该参数指定微分函数
x.grad.zero_()

In [9]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [11]:
y = x * x  # 这里的y不是一个标量，这是一个向量
print(y)

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


In [10]:
y.sum()

tensor(14., grad_fn=<SumBackward0>)

In [8]:
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()  # y.sum()后就讲向量转为标量了，对标量求导
x.grad

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([0., 2., 4., 6.])

In [21]:
x = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(x, x)
y.backward()
x.grad.zero_()
y = x * x
print(y)

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


In [22]:
u = y.detach()  # y.detach把y当作一个常数，而不是关于x的一个函数
u

tensor([0., 1., 4., 9.])

In [23]:
z = u * x

In [24]:
z

tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)

In [25]:
z.sum().backward()

In [27]:
x.grad == u

tensor([True, True, True, True])

In [28]:
def f(a):
    b = a * 2
    while b.norm() < 1000:  # norm是L2范数
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [29]:
a = torch.randn(size=(), requires_grad=True)
print(a)

tensor(-0.1460, requires_grad=True)


In [32]:
b = 2 * a
b.norm()

tensor(0.2920, grad_fn=<CopyBackwards>)

In [33]:
b * 2

tensor(-0.5840, grad_fn=<MulBackward0>)

In [31]:
d = f(a)
d

tensor(-119611.1328, grad_fn=<MulBackward0>)

In [34]:
d.backward()
print(a.grad)

tensor(819200.)


In [35]:
print(d/a)

tensor(819200., grad_fn=<DivBackward0>)


In [36]:
a.grad == d/a # d是a的线性函数，所以导数就是斜率d/a

tensor(True)