In [1]:
import torch
from torch import nn

In [2]:
def comp_conv2d(conv2d, X):  # conv2d 作为传参传进去，在内部使用
    X = X.reshape((1, 1) + X.shape)  # 在维度前面加入一个通道数和批量大小数
    Y = conv2d(X)  # 卷积处理是一个四维的矩阵
    return Y.reshape(Y.shape[2:])  # 将前面两个维度拿掉

In [3]:
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1)  # padding=1 为左右都填充一行
X = torch.rand(size=(8, 8))
print(comp_conv2d(conv2d, X).shape)

torch.Size([8, 8])


In [4]:
conv2d = nn.Conv2d(1, 1, kernel_size=(5, 3), padding=(2, 1))
print(comp_conv2d(conv2d, X).shape)

torch.Size([8, 8])


In [5]:
# 将高度和宽度的步幅设置为2
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)
print(comp_conv2d(conv2d, X).shape)

torch.Size([4, 4])


In [6]:
# 一个稍微复杂的例子
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
print(comp_conv2d(conv2d, X).shape)

torch.Size([2, 2])


In [7]:
from d2l import torch as d2l

In [8]:
# 多通道输入运算
def corr2d_multi_in(X, K):
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))  # X,K为3通道矩阵，for使得对最外面通道进行遍历

In [9]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
                  [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])
print(corr2d_multi_in(X, K))

tensor([[ 56.,  72.],
        [104., 120.]])


In [10]:
# 多输出通道运算
def corr2d_multi_in_out(X, K):  # X为3通道矩阵，K为4通道矩阵，最外面维为输出通道
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)  # 大k中每个小k是一个3D的Tensor。0表示stack堆叠函数里面在0这个维度堆叠。

In [11]:
print(K.shape)

torch.Size([2, 2, 2])


In [12]:
print((K + 1).shape)
print((K + 2).shape)

torch.Size([2, 2, 2])
torch.Size([2, 2, 2])


In [13]:
print(K)
print(K + 1)

tensor([[[0., 1.],
         [2., 3.]],

        [[1., 2.],
         [3., 4.]]])
tensor([[[1., 2.],
         [3., 4.]],

        [[2., 3.],
         [4., 5.]]])


In [14]:
K = torch.stack((K, K + 1, K + 2), 0)  # K与K+1之间的区别为K的每个元素加1

In [15]:
print(K.shape)

torch.Size([3, 2, 2, 2])


In [16]:
print(corr2d_multi_in_out(X, K))

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])


In [17]:
print(X.shape)

torch.Size([2, 3, 3])


In [18]:
# 1x1卷积
def comp_conv2d(conv2d, X):  # conv2d 作为传参传进去，在内部使用
    X = X.reshape((1, 1) + X.shape)  # 在维度前面加入一个通道数和批量大小数
    Y = conv2d(X)  # 卷积处理是一个四维的矩阵
    return Y.reshape(Y.shape[2:])  # 将前面两个维度拿掉


X = torch.rand(size=(8, 8))
conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=2)  # Pytorch里面卷积函数的第一个参数为输出通道，第二个参数为输入通道
print(comp_conv2d(conv2d, X).shape)

conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))  # 一个稍微复杂的例子
print(comp_conv2d(conv2d, X).shape)

torch.Size([4, 4])
torch.Size([2, 2])
