In [1]:
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
import pandas as pd

pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [2]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [3]:
result_ = scaler.fit_transform(data)

In [4]:
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [5]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [7]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler(feature_range=(5, 10))
result = scaler.fit_transform(data)

In [8]:
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [9]:
import numpy as np

X = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])

In [10]:
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

In [11]:
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [12]:
# 逆转归一化
X_returned = X_nor * ((X.max(axis=0) - X.min(axis=0)) + X.min(axis=0))

In [13]:
X_returned

array([[ 0.  ,  0.  ],
       [ 0.25,  4.5 ],
       [ 0.5 ,  9.  ],
       [ 1.  , 18.  ]])